name: Bump dependencies

on:
  schedule:
    - cron: "0 12 * * 1"

jobs:
  bump-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '16'
      - name: Install Leiningen
        run: |
          curl -O https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
          chmod +x lein
          mv lein /usr/local/bin/lein
      - name: Setup GPG
        id: setup_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          node-version: '16'
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Bump dependencies
        env:
          ANCIENT_UPGRADE_OUTPUT: ${{ steps.bump-dependencies-output.outputs.upgrade-output }}
        run: |
          echo "$ANCIENT_UPGRADE_OUTPUT" | tee /dev/stderr | grep -q 'No outdated dependencies.' || \
          { \
            echo "Updating outdated dependencies..." ; \
            lein ancient upgrade ; \
            echo "Saving the output of lein ancient upgrade..." ; \
            echo "upgrade-output=$?" >> $GITHUB_ENV ; \
          }
      - id: bump-dependencies-output
        run: |
          echo "Nothing to commit, exiting" | tee /dev/stderr
          echo "upgrade-output=0" >> $GITHUB_ENV
        if: env.upgrade-output == '0'
      - name: Commit changes
        run: |
          git config --local user.email "caio.cascaes@gmail.com"
          git config --local user.name "Caio Cascaes"
          git add project.clj
          git commit -S -m "Bump dependencies"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          node-version: '16'
          title: "Bump dependencies"
          body: "This pull request bumps the dependencies to the latest versions."
          reviewers: "deafjava"
          assignees: "deafjava"
          base: "main"
          token: ${{ secrets.GITHUB_TOKEN }}
