name: Bump dependencies

on:
  schedule:
    - cron: "0 12 * * 1"

jobs:
  bump-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Leiningen
        run: |
          curl -O https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
          chmod +x lein
          mv lein /usr/local/bin/lein
      - name: Bump dependencies
        run: lein ancient upgrade
      - name: Commit changes
        run: |
          CHANGES=$(git diff --shortstat 2> /dev/null | tail -n1)
          if [ -n "$CHANGES" ]; then
            git config --local user.email "caio.cascaes@gmail.com"
            git config --local user.name "Caio Cascaes"
            git add project.clj
            git commit -m "Bump dependencies"
          else
            echo "Nothing to commit, exiting"
            exit 0
          fi
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Bump dependencies"
          body: "This pull request bumps the dependencies to the latest versions."
          reviewers: "deafjava"
          assignees: "deafjava"
          base: "main"
          token: ${{ secrets.GITHUB_TOKEN }}
