name: Bump dependencies

on:
  schedule:
    - cron: "0 12 * * 1"

jobs:
  bump-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Leiningen
        run: |
          curl -O https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
          chmod +x lein
          sudo mv lein /usr/local/bin/lein

      - name: Setup GPG
        id: setup_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Bump dependencies
        run: |
          lein ancient upgrade || echo "No outdated dependencies to update"

      - name: Commit and push changes
        id: commit
        run: |
          git config --local user.email "caio.cascaes@gmail.com"
          git config --local user.name "Caio Cascaes"
          git diff --quiet && git diff --staged --quiet || (git add . && git commit -S -m "Bump dependencies" && echo "::set-output name=push::true")
        continue-on-error: true

      - name: Create pull request
        id: cpr
        if: steps.commit.outputs.push == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Bump dependencies"
          body: "This pull request bumps the dependencies to the latest versions."
          reviewers: "deafjava"
          assignees: "deafjava"
          base: "main"
          token: ${{ secrets.GITHUB_TOKEN }}
