name: Update Angular and open Pull Request

on:
  schedule:
    - cron: "0 12 * * 1"
  push:
    branches:
      - main

jobs:
  update-angular:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install NPM Dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Update Angular
        run: ng update @angular/core@latest

      - name: Commit changes and Push
        id: commit
        run: |
          git config --local user.email "caio.cascaes@gmail.com"
          git config --local user.name "Caio Cascaes"
          git diff --quiet && git diff --staged --quiet || (git add . && git commit -S -m "Bump Angular version" && echo "::set-output name=push::true")
        continue-on-error: true

      - name: Create Pull Request
        if: steps.commit.outputs.push == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update Angular"
          body: "This pull request updates Angular to the latest version.  \n![](https://media.giphy.com/media/VdU7TZDHmWUTtFq2Mz/giphy.gif)"
          reviewers: "deafjava"
          assignees: "deafjava"
          base: "main"
          token: ${{ secrets.GITHUB_TOKEN }}
