name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    needs: [ checkout ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install Leiningen
        run: |
          curl -O https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
          chmod +x lein
          mv lein /usr/local/bin/lein
      - name: Lint
        run: lein lint
